export const TableMockup = [
  {
    orderid: "123456",
    sitename: "Home Build.",
    Deliverydate: "22-06-22",
    loads: "36t",
    driver: "lee",
    rupess: "$1520",
    Jobstatus: "Completed",
    paymentstatus: "Paid",
  },
  {
    orderid: "123456",
    sitename: "KS Infra Ltd.",
    Deliverydate: "22-06-22",
    loads: "36t",
    driver: "lee",
    rupess: "$1520",
    Jobstatus: "UnCompleted",
    paymentstatus: "UnPaid",
  },
  {
    orderid: "123456",
    sitename: "KS Infra Ltd.",
    Deliverydate: "22-06-22",
    loads: "36t",
    driver: "lee",
    rupess: "$1520",
    Jobstatus: "Completed",
    paymentstatus: "Paid",
  },
  {
    orderid: "123456",
    sitename: "KS Infra Ltd.",
    Deliverydate: "22-06-22",
    loads: "36t",
    driver: "lee",
    rupess: "$1520",
    Jobstatus: "UnCompleted",
    paymentstatus: "UnPaid",
  },
];
